language: node_js
node_js:
- 'iojs'
services:
  - mongodb
before_script:
  - sleep 1
before_install:
  - npm install jspm -g && cd Moonridge-client && npm install && cd ..
deploy:
  provider: npm
  email: capajj@gmail.com
  on:
    tags: true
    repo: capaj/Moonridge
    all_branches: true
