language: node_js
node_js:
- '0.10'
- '0.11'
before_install:
  - npm install jspm -g && cd test/e2e-smoketest && npm install && cd ../..
deploy:
  provider: npm
  email: capajj@gmail.com
  on:
    tags: true
    repo: capaj/moonridge
    all_branches: true